---
- name: Test Ansible Connection
  hosts: all
  gather_facts: yes
  tasks:
    - name: Test connection
      ping:

    - name: Display system information
      debug:
        msg: "Connected to {{ inventory_hostname }} running {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Check if kubectl is installed
      command: kubectl version --client
      register: kubectl_check
      ignore_errors: yes

    - name: Display kubectl status
      debug:
        msg: "kubectl is {{ 'installed' if kubectl_check.rc == 0 else 'not installed' }}"
