apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM= # postgres123
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtanN0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg== # your-super-secret-jwt-key-change-in-production
  JWT_REFRESH_SECRET: eW91ci1zdXBlci1zZWNyZXQtcmVmcmVzaC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24= # your-super-secret-refresh-key-change-in-production

  # AWS Configuration (replace with actual values)
  AWS_ACCESS_KEY_ID: eW91ci1hd3MtYWNjZXNzLWtleQ== # your-aws-access-key
  AWS_SECRET_ACCESS_KEY: eW91ci1hd3Mtc2VjcmV0LWtleQ== # your-aws-secret-key
  S3_BUCKET: eW91ci1lY29tbWVyY2UtYnVja2V0 # your-ecommerce-bucket
  CLOUDFRONT_DOMAIN: eW91ci1jbG91ZGZyb250LWRvbWFpbg== # your-cloudfront-domain

  # Email Configuration
  SMTP_HOST: c210cC5nbWFpbC5jb20= # smtp.gmail.com
  SMTP_PORT: NTg3 # 587
  SMTP_USER: eW91ci1lbWFpbEBnbWFpbC5jb20= # your-email@gmail.com
  SMTP_PASS: eW91ci1hcHAtcGFzc3dvcmQ= # your-app-password

  # Payment Gateway
  RAZORPAY_KEY_ID: eW91ci1yYXpvcnBheS1rZXktaWQ= # your-razorpay-key-id
  RAZORPAY_KEY_SECRET: eW91ci1yYXpvcnBheS1rZXktc2VjcmV0 # your-razorpay-key-secret
